<?php

declare(strict_types=1);

/**
 * EN→TR YEREL SÖZLÜK (İE#14 A2 · K56 Katman 1 — İNGİLİZCE KAYNAKLAR).
 *
 * NEDEN ŞİMDİDEN: 1688 Çince gelir ama Alibaba.com, AliExpress ve Amazon
 * öznitelikleri İNGİLİZCE gelir (F37 kaynak site modülleri). Aynı belirlenimci
 * hat o platformlar eklendiğinde hazır olsun diye kapalı kümeler burada da
 * tanımlıdır — kod tarafında tek fark kaynak dil kodudur.
 *
 * Eşleşme TAM METİN ve BÜYÜK/KÜÇÜK HARF DUYARSIZDIR (anahtarlar küçük harf
 * yazılır; Glossary aramadan önce metni küçültür).
 *
 * ÇEVRİLMEZ (K56): marka adı, model/parça kodu, ölçü-sayı-birim, ilan no.
 */
return [
    // ── Malzeme ──
    'stainless steel' => 'Paslanmaz çelik',
    '304 stainless steel' => '304 paslanmaz çelik',
    '316 stainless steel' => '316 paslanmaz çelik',
    'alloy' => 'Alaşım',
    'aluminum alloy' => 'Alüminyum alaşım',
    'aluminium alloy' => 'Alüminyum alaşım',
    'zinc alloy' => 'Çinko alaşım',
    'plastic' => 'Plastik',
    'abs' => 'ABS plastik',
    'abs plastic' => 'ABS plastik',
    'pvc' => 'PVC',
    'pp' => 'PP (polipropilen)',
    'pe' => 'PE (polietilen)',
    'silicone' => 'Silikon',
    'rubber' => 'Kauçuk',
    'glass' => 'Cam',
    'ceramic' => 'Seramik',
    'wood' => 'Ahşap',
    'wooden' => 'Ahşap',
    'bamboo' => 'Bambu',
    'leather' => 'Deri',
    'pu leather' => 'PU deri',
    'genuine leather' => 'Hakiki deri',
    'cotton' => 'Pamuk',
    'polyester' => 'Polyester',
    'nylon' => 'Naylon',
    'carbon steel' => 'Karbon çelik',
    'iron' => 'Demir',
    'copper' => 'Bakır',
    'brass' => 'Pirinç',
    'paper' => 'Kâğıt',
    'cardboard' => 'Karton',
    'metal' => 'Metal',

    // ── Renk ──
    'white' => 'Beyaz',
    'black' => 'Siyah',
    'grey' => 'Gri',
    'gray' => 'Gri',
    'silver' => 'Gümüş',
    'gold' => 'Altın',
    'golden' => 'Altın',
    'red' => 'Kırmızı',
    'blue' => 'Mavi',
    'navy' => 'Lacivert',
    'navy blue' => 'Lacivert',
    'green' => 'Yeşil',
    'yellow' => 'Sarı',
    'pink' => 'Pembe',
    'purple' => 'Mor',
    'orange' => 'Turuncu',
    'brown' => 'Kahverengi',
    'beige' => 'Bej',
    'transparent' => 'Şeffaf',
    'clear' => 'Şeffaf',
    'multicolor' => 'Çok renkli',
    'multi-color' => 'Çok renkli',
    'assorted colors' => 'Karışık renk',

    // ── Menşe ──
    'china' => 'Çin',
    'mainland china' => 'Çin',
    'made in china' => 'Çin malı',
    'zhejiang' => 'Zhejiang',
    'guangdong' => 'Guangdong',
    'jiangsu' => 'Jiangsu',
    'fujian' => 'Fujian',
    'shandong' => 'Shandong',
    'yiwu' => 'Yiwu',
    'shenzhen' => 'Shenzhen',
    'guangzhou' => 'Guangzhou',
    'ningbo' => 'Ningbo',
    'turkey' => 'Türkiye',
    'india' => 'Hindistan',
    'vietnam' => 'Vietnam',

    // ── Birim ──
    'piece' => 'adet',
    'pieces' => 'adet',
    'pcs' => 'adet',
    'pc' => 'adet',
    'unit' => 'adet',
    'set' => 'takım',
    'sets' => 'takım',
    'pair' => 'çift',
    'pairs' => 'çift',
    'pack' => 'paket',
    'carton' => 'koli',
    'cartons' => 'koli',
    'box' => 'kutu',
    'bag' => 'poşet',
    'meter' => 'metre',
    'meters' => 'metre',
    'kilogram' => 'kg',
    'gram' => 'gram',
    'liter' => 'litre',
    'litre' => 'litre',
    'milliliter' => 'ml',

    // ── Ambalaj ──
    'color box' => 'Renkli kutu',
    'colour box' => 'Renkli kutu',
    'white box' => 'Beyaz kutu',
    'neutral packaging' => 'Nötr ambalaj',
    'oem packaging' => 'OEM ambalaj',
    'plastic bag' => 'Plastik poşet',
    'carton box' => 'Karton koli',
    'bubble bag' => 'Baloncuklu poşet',
    'blister' => 'Blister',
    'blister packaging' => 'Blister ambalaj',
    'individual packaging' => 'Tekli ambalaj',
    'gift box' => 'Hediye kutusu',
    'bulk packaging' => 'Dökme ambalaj',
    'opp bag' => 'OPP poşet',

    // ── Sertifika / özellik ──
    'ce certified' => 'CE sertifikalı',
    'ce' => 'CE',
    'rohs' => 'RoHS',
    'fcc' => 'FCC',
    'fda' => 'FDA',
    'iso9001' => 'ISO 9001',
    'food grade' => 'Gıdaya uygun',
    'medical grade' => 'Tıbbi sınıf',
    'waterproof' => 'Su geçirmez',
    'water resistant' => 'Suya dayanıklı',
    'dustproof' => 'Toz geçirmez',
    'rechargeable' => 'Şarj edilebilir',
    'wireless' => 'Kablosuz',
    'wired' => 'Kablolu',
    'foldable' => 'Katlanabilir',
    'portable' => 'Taşınabilir',
    'reusable' => 'Tekrar kullanılabilir',
    'disposable' => 'Tek kullanımlık',
    'eco-friendly' => 'Çevre dostu',
    'handmade' => 'El yapımı',
    'customized' => 'Özel üretim',
    'in stock' => 'Stokta',

    // ── Öznitelik ADLARI (etiket) ──
    'brand' => 'Marka',
    'brand name' => 'Marka',
    'model' => 'Model',
    'model number' => 'Model',
    'material' => 'Malzeme',
    'color' => 'Renk',
    'colour' => 'Renk',
    'size' => 'Ölçü',
    'dimensions' => 'Ölçü',
    'weight' => 'Ağırlık',
    'net weight' => 'Net ağırlık',
    'gross weight' => 'Brüt ağırlık',
    'place of origin' => 'Menşe',
    'origin' => 'Menşe',
    'capacity' => 'Kapasite',
    'power' => 'Güç',
    'voltage' => 'Voltaj',
    'warranty' => 'Garanti',
    'certification' => 'Sertifika',
    'packaging' => 'Ambalaj',
    'application' => 'Kullanım alanı',
    'usage' => 'Kullanım yeri',
    'item no' => 'Stok kodu',
    'sku' => 'Stok kodu',
    'specification' => 'Varyasyon',
    'moq' => 'Asgari sipariş',
    'minimum order quantity' => 'Asgari sipariş',
    'units per carton' => 'Koli içi adet',
    'lead time' => 'Termin süresi',
    'payment terms' => 'Ödeme koşulu',
    'shipping' => 'Kargo',
];
